### PR TITLE
No bundler warnings

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
Avoid using method deprecated in recent bundler versions.

I also added MacOS to the CI because I can't reproduce the CI issues locally and I'm using MacOS, so I want to double check whether it could be related to the OS somehow.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
Ok, I can repro test failures now, will work on this.

**Comment by deivid-rodriguez** [comment]
I built https://github.com/takari/polyglot-maven/pull/236 locally with the idea of using it here to see if that fixes the CI, but got the following error:

```
[ERROR] Failed to execute goal de.saumya.mojo:gem-maven-plugin:2.0.0-1:initialize (default) on project polyglot-ruby: Execution default of goal de.saumya.mojo:gem-maven-plugin:2.0.0-1:initialize failed: Unable to load the mojo 'initialize' in the plugin 'de.saumya.mojo:gem-maven-plugin:2.0.0-1' due to an API incompatibility: org.codehaus.plexus.component.repository.exception.ComponentLookupException: de/saumya/mojo/gem/InitializeMojo has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

Could it be that `gem-maven-plugin:2.0.0-1` has actually dropped support for Java 8 while adding support for Java 11? Does that make sense?

**Comment by kares** [comment]
@deivid-rodriguez that is actually correct - seems that the parent (for gem-maven-plugin) is [compiling with 11](https://github.com/torquebox/jruby-maven-plugins/blob/d24be9d0a42b563777fed3a6a6a0f4c944b4e12f/parent-mojo/pom.xml#L111-L112) (not sure why)

**Comment by deivid-rodriguez** [comment]
It was because of an incorrect change I made that somehow sneaked into the 2.0.0 release. I think it was just an oversight. I was just working on a WIP PR on adding Java 11 support but didn't intend to drop support for java 8 at all. Hopefully we can get the changes in https://github.com/torquebox/jruby-maven-plugins/pull/119 released to get support for Java 8 restored!

**Comment by deivid-rodriguez** [comment]
`jruby-maven-plugins 2.0.1` was released and I updated https://github.com/takari/polyglot-maven/pull/236 to use it, but even using a locally built `polyglot-ruby` using that, old dependencies are still being pulled and I'm unsure why. In particular,mavengem-wagon 0.2.1, which brings gem-maven-plugins 1.1.5, which we want to avoid. 🤔

**Comment by deivid-rodriguez** [comment]
I'm pretty sure it's coming from here: https://github.com/torquebox/maven-tools/blob/b52405ed1bb73fec626c631a18ea40045d6b6816/lib/maven/tools/versions.rb#L27-L32.

We most likely also need to bump those dependencies, get a new version out, and then bump `polyglot-ruby` dependency on it as well.

**Comment by deivid-rodriguez** [comment]
I created another PR for maven-tools: https://github.com/torquebox/maven-tools/pull/34. That one was tricky because building `maven-tools` locally was using the broken latest release of `maven-tools`. To fix this chicken-and-egg issue, I migrated `maven-tools` to use a plain `pom.xml` file instead of a `Mavenfile`.

**Comment by deivid-rodriguez** [comment]
I will verify it later, but I think now once https://github.com/takari/polyglot-maven/pull/237 is merged and released and we bump the `polyglot-ruby` dependency here, we'll have a green CI.

**Comment by deivid-rodriguez** [comment]
It tested locally against a locally built version of `polyglot-ruby` including https://github.com/takari/polyglot-maven/pull/237, and it's all green 🎉.

So we just need to wait for https://github.com/takari/polyglot-maven/pull/237 to be released.

**Comment by deivid-rodriguez** [comment]
polyglot-ruby 0.4.8 has been released and I updated `ruby-maven` to use it, but now CI fails sometimes and passes others. I'll try figure out why.

**Comment by deivid-rodriguez** [comment]
Alright, so test errors didn't suggest any issues with this library. Tests were running `mvn` commands and checking different things being included in the output, however, the log file were the output was being saved (passed through the `-l` parameter to `mvn`) sometimes was not getting generated for some reason (my guess is some issue with `mvn` itself).

Since passing `-l` or using the `CatchStdout` class that would change `$stdout` and `$stderr`, I switched both to a more standard approach of using `minitest` methods `capture_subprocess_io` or `capture_io` and now everything is green 🎉.

@headius With the changes in this PR, there should no longer be any issues when releasing version 3.3.13. Let me know!

**Comment by headius** [comment]
Thanks so much for the footwork here, @deivid-rodriguez! I will merge this.

**Comment by headius** [comment]
@mkristian Are you still out there? We still are willing to help take over maintenance if we can get a tour and all the appropriate push rights.

**Comment by mkristian** [comment]
@headius I am still out there and did help @deivid-rodriguez as much I could the recent weeks. but we also can schedule some meeting so I give you guys some tour !

**Comment by deivid-rodriguez** [comment]
Thanks @headius and @mkristian!

@headius You are an owner of this gem as per https://rubygems.org/gems/ruby-maven, so you should be all good for releasing. I don't think releasing this gem needs anything to be pushed to maven servers, in case you're lacking some push rights there.

**Comment by AndyObtiva** [comment]
Hi, 

I just wanted to note that in the newly released JRuby 9.3.3.0, I still get into an issue with ruby-maven when installing psych v4.0.3:
```
using maven for the first time results in maven
downloading all its default plugin and can take time.
as those plugins get cached on disk and further execution
of maven is much faster then the first time.

[DEPRECATED] `Bundler.with_clean_env` has been deprecated in favor of `Bundler.with_unbundled_env`. If you instead want the environment before bundler was originally loaded, use `Bundler.with_original_env` (called at /Users/andymaleh/.rvm/gems/jruby-9.3.3.0@glimmer-dsl-swt/gems/ruby-maven-3.3.12/lib/ruby_maven.rb:38)
Using warbler 2.0.5
unsupported Java version "17", defaulting to 1.7
[ERROR] Internal error: org.jruby.exceptions.RaiseException: (LoadError) library `java' could not be loaded: java.lang.reflect.InaccessibleObjectException: Unable to make protected native java.lang.Object java.lang.Object.clone() throws java.lang.CloneNotSupportedException accessible: module java.base does not "opens java.lang" to unnamed module @34819867 -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: org.jruby.exceptions.RaiseException: (LoadError) library `java' could not be loaded: java.lang.reflect.InaccessibleObjectException: Unable to make protected native java.lang.Object java.lang.Object.clone() throws java.lang.CloneNotSupportedException accessible: module java.base does not "opens java.lang" to unnamed module @34819867
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:121)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.jruby.exceptions.RaiseException: (LoadError) library `java' could not be loaded: java.lang.reflect.InaccessibleObjectException: Unable to make protected native java.lang.Object java.lang.Object.clone() throws java.lang.CloneNotSupportedException accessible: module java.base does not "opens java.lang" to unnamed module @34819867
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
Errno::ENOENT: No such file or directory - /Users/andymaleh/.rvm/gems/jruby-9.3.3.0@glimmer-dsl-swt/gems/psych-4.0.3-java/deps.lst
  org/jruby/RubyIO.java:1227:in `sysopen'
  org/jruby/RubyIO.java:3986:in `read'
  /Users/andymaleh/.rvm/rubies/jruby-9.3.3.0/lib/ruby/stdlib/jars/installer.rb:69:in `load_from_maven'
  /Users/andymaleh/.rvm/rubies/jruby-9.3.3.0/lib/ruby/stdlib/jars/installer.rb:235:in `install_dependencies'
  /Users/andymaleh/.rvm/rubies/jruby-9.3.3.0/lib/ruby/stdlib/jars/installer.rb:224:in `do_install'
  /Users/andymaleh/.rvm/rubies/jruby-9.3.3.0/lib/ruby/stdlib/jars/installer.rb:170:in `vendor_jars'
  /Users/andymaleh/.rvm/rubies/jruby-9.3.3.0/lib/ruby/stdlib/jars/post_install_hook.rb:28:in `block in <main>'
  /Users/andymaleh/.rvm/rubies/jruby-9.3.3.0/lib/ruby/stdlib/rubygems/installer.rb:367:in `block in run_post_install_hooks'
  org/jruby/RubyArray.java:1865:in `each'
  /Users/andymaleh/.rvm/rubies/jruby-9.3.3.0/lib/ruby/stdlib/rubygems/installer.rb:366:in `run_post_install_hooks'
  /Users/andymaleh/.rvm/gems/jruby-9.3.3.0@glimmer-dsl-swt/gems/bundler-2.3.5/lib/bundler/rubygems_gem_installer.rb:43:in `install'
  /Users/andymaleh/.rvm/gems/jruby-9.3.3.0@glimmer-dsl-swt/gems/bundler-2.3.5/lib/bundler/source/rubygems.rb:204:in `install'
  /Users/andymaleh/.rvm/gems/jruby-9.3.3.0@glimmer-dsl-swt/gems/bundler-2.3.5/lib/bundler/installer/gem_installer.rb:54:in `install'
  /Users/andymaleh/.rvm/gems/jruby-9.3.3.0@glimmer-dsl-swt/gems/bundler-2.3.5/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /Users/andymaleh/.rvm/gems/jruby-9.3.3.0@glimmer-dsl-swt/gems/bundler-2.3.5/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /Users/andymaleh/.rvm/gems/jruby-9.3.3.0@glimmer-dsl-swt/gems/bundler-2.3.5/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /Users/andymaleh/.rvm/gems/jruby-9.3.3.0@glimmer-dsl-swt/gems/bundler-2.3.5/lib/bundler/worker.rb:62:in `apply_func'
  /Users/andymaleh/.rvm/gems/jruby-9.3.3.0@glimmer-dsl-swt/gems/bundler-2.3.5/lib/bundler/worker.rb:57:in `block in process_queue'
  org/jruby/RubyKernel.java:1507:in `loop'
  /Users/andymaleh/.rvm/gems/jruby-9.3.3.0@glimmer-dsl-swt/gems/bundler-2.3.5/lib/bundler/worker.rb:54:in `process_queue'
  /Users/andymaleh/.rvm/gems/jruby-9.3.3.0@glimmer-dsl-swt/gems/bundler-2.3.5/lib/bundler/worker.rb:91:in `block in create_threads'
```

## Environment

```
Bundler             2.3.5
  Platforms         ruby, universal-java-17
Ruby                2.6.8p0 (2022-01-19 revision 67951) [java]
  Full Path         /Users/andymaleh/.rvm/rubies/jruby-9.3.3.0/bin/jruby
  Config Dir        /Users/andymaleh/.rvm/rubies/jruby-9.3.3.0/etc
RubyGems            3.2.29
  Gem Home          /Users/andymaleh/.rvm/gems/jruby-9.3.3.0@glimmer-dsl-swt
  Gem Path          /Users/andymaleh/.rvm/gems/jruby-9.3.3.0@glimmer-dsl-swt:/Users/andymaleh/.rvm/rubies/jruby-9.3.3.0/lib/ruby/gems/shared
  User Home         /Users/andymaleh
  User Path         /Users/andymaleh/.gem/jruby/2.6.0
  Bin Dir           /Users/andymaleh/.rvm/gems/jruby-9.3.3.0@glimmer-dsl-swt/bin
OpenSSL             
  Compiled          JRuby-OpenSSL 0.11.0
  Loaded            JRuby-OpenSSL 0.11.0
  Cert File         /Library/Java/JavaVirtualMachines/jdk-17.0.1.jdk/Contents/Home/lib/security/cacerts
  Cert Dir          /etc/ssl/certs
Tools               
  Git               2.24.3 (Apple Git-128)
  RVM               1.29.12-next (master)
  rbenv             not installed
  chruby            not installed
  rubygems-bundler  (1.4.5)
```

## Bundler Build Metadata

```
Built At          2022-01-12
Git SHA           a13d015fcb
Released Version  true
```

## Gemfile

### Gemfile

```ruby
source 'http://rubygems.org'

ruby '>= 2.6.0', :engine => 'jruby', engine_version: '>= 9.3.0.0'

# Glimmer project owner gems
gem 'glimmer', '~> 2.5.5'
gem 'super_module', '>= 1.4.1', '< 2.0.0'
gem 'nested_inherited_jruby_include_package', '>= 0.3.0', '< 2.0.0'
gem 'puts_debuggerer', '>= 0.13.0', '< 2.0.0', require: false
gem 'rake-tui', '>= 0.2.3', '< 2.0.0'

# 3rd party gems (flexible versions to support other user gems that may share dependencies)
gem 'concurrent-ruby', '>= 1.1.7', '< 2.0.0'
gem 'jruby-win32ole', '>= 0.8.5', '< 2.0.0'
gem 'os', '>= 1.0.0', '< 2.0.0'
gem 'rake', '>= 13.0.0'
gem 'text-table', '>= 1.2.4', '< 2.0.0'
gem 'rouge', '>= 3.26.0', '< 4.0.0'

group :development do
  gem 'juwelier', '>= 2.4.9', '< 3.0.0'
  gem 'warbler', '>= 2.0.5', '< 3.0.0'
  gem 'rspec-mocks', '~> 3.0'
  gem 'rspec', '~> 3.0'
  gem 'coveralls', '= 0.8.23', require: false
  gem 'simplecov', '~> 0.16.1', require: nil
  gem 'simplecov-lcov', '~> 0.7.0', require: nil
end
```

### Gemfile.lock

```
GEM
  remote: http://rubygems.org/
  specs:
    addressable (2.8.0)
      public_suffix (>= 2.0.2, < 5.0)
    array_include_methods (1.4.0)
    awesome_print (1.9.2)
    builder (3.2.4)
    concurrent-ruby (1.1.9)
    coveralls (0.8.23)
      json (>= 1.8, < 3)
      simplecov (~> 0.16.1)
      term-ansicolor (~> 1.3)
      thor (>= 0.19.4, < 2.0)
      tins (~> 1.6)
    descendants_tracker (0.0.4)
      thread_safe (~> 0.3, >= 0.3.1)
    diff-lcs (1.4.4)
    docile (1.4.0)
    facets (3.1.0)
    faraday (1.8.0)
      faraday-em_http (~> 1.0)
      faraday-em_synchrony (~> 1.0)
      faraday-excon (~> 1.1)
      faraday-httpclient (~> 1.0.1)
      faraday-net_http (~> 1.0)
      faraday-net_http_persistent (~> 1.1)
      faraday-patron (~> 1.0)
      faraday-rack (~> 1.0)
      multipart-post (>= 1.2, < 3)
      ruby2_keywords (>= 0.0.4)
    faraday-em_http (1.0.0)
    faraday-em_synchrony (1.0.0)
    faraday-excon (1.1.0)
    faraday-httpclient (1.0.1)
    faraday-net_http (1.0.1)
    faraday-net_http_persistent (1.2.0)
    faraday-patron (1.0.0)
    faraday-rack (1.0.0)
    git (1.9.1)
      rchardet (~> 1.8)
    github_api (0.19.0)
      addressable (~> 2.4)
      descendants_tracker (~> 0.0.4)
      faraday (>= 0.8, < 2)
      hashie (~> 3.5, >= 3.5.2)
      oauth2 (~> 1.0)
    glimmer (2.5.5)
      array_include_methods (~> 1.4.0)
      facets (>= 3.1.0, < 4.0.0)
    hashie (3.6.0)
    highline (2.0.3)
    jar-dependencies (0.4.1)
    jruby-jars (9.3.1.0)
    jruby-rack (1.1.21)
    jruby-win32ole (0.8.5)
    json (2.6.1-java)
    juwelier (2.4.9)
      builder
      bundler
      git
      github_api
      highline
      kamelcase (~> 0)
      nokogiri
      psych
      rake
      rdoc
      semver2
    jwt (2.3.0)
    kamelcase (0.0.2)
      semver2 (~> 3)
    method_source (1.0.0)
    multi_json (1.15.0)
    multi_xml (0.6.0)
    multipart-post (2.1.1)
    nested_inherited_jruby_include_package (0.3.0)
    nokogiri (1.12.5-java)
      racc (~> 1.4)
    oauth2 (1.4.7)
      faraday (>= 0.8, < 2.0)
      jwt (>= 1.0, < 3.0)
      multi_json (~> 1.3)
      multi_xml (~> 0.5)
      rack (>= 1.2, < 3)
    os (1.1.4)
    pastel (0.8.0)
      tty-color (~> 0.5)
    psych (3.3.2-java)
      jar-dependencies (>= 0.1.7)
    public_suffix (4.0.6)
    puts_debuggerer (0.13.1)
      awesome_print (~> 1.9.2)
    racc (1.6.0-java)
    rack (2.2.3)
    rake (13.0.6)
    rake-tui (0.2.3)
      tty-prompt
    rchardet (1.8.0)
    rdoc (6.3.3)
    rouge (3.26.1)
    rspec (3.10.0)
      rspec-core (~> 3.10.0)
      rspec-expectations (~> 3.10.0)
      rspec-mocks (~> 3.10.0)
    rspec-core (3.10.1)
      rspec-support (~> 3.10.0)
    rspec-expectations (3.10.1)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.10.0)
    rspec-mocks (3.10.2)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.10.0)
    rspec-support (3.10.3)
    ruby2_keywords (0.0.5)
    rubyzip (1.3.0)
    semver2 (3.4.2)
    simplecov (0.16.1)
      docile (~> 1.1)
      json (>= 1.8, < 3)
      simplecov-html (~> 0.10.0)
    simplecov-html (0.10.2)
    simplecov-lcov (0.7.0)
    super_module (1.4.1)
      method_source (>= 0.8.2, < 1.1.0)
    sync (0.5.0)
    term-ansicolor (1.7.1)
      tins (~> 1.0)
    text-table (1.2.4)
    thor (1.1.0)
    thread_safe (0.3.6-java)
    tins (1.29.1)
      sync
    tty-color (0.6.0)
    tty-cursor (0.7.1)
    tty-prompt (0.23.1)
      pastel (~> 0.8)
      tty-reader (~> 0.8)
    tty-reader (0.9.0)
      tty-cursor (~> 0.7)
      tty-screen (~> 0.8)
      wisper (~> 2.0)
    tty-screen (0.8.1)
    warbler (2.0.5)
      jruby-jars (>= 9.0.0.0)
      jruby-rack (>= 1.1.1, < 1.3)
      rake (>= 10.1.0)
      rubyzip (~> 1.0, < 1.4)
    wisper (2.0.1)

PLATFORMS
  universal-java-1.8
  universal-java-16
  universal-java-17

DEPENDENCIES
  concurrent-ruby (>= 1.1.7, < 2.0.0)
  coveralls (= 0.8.23)
  glimmer (~> 2.5.5)
  jruby-win32ole (>= 0.8.5, < 2.0.0)
  juwelier (>= 2.4.9, < 3.0.0)
  nested_inherited_jruby_include_package (>= 0.3.0, < 2.0.0)
  os (>= 1.0.0, < 2.0.0)
  puts_debuggerer (>= 0.13.0, < 2.0.0)
  rake (>= 13.0.0)
  rake-tui (>= 0.2.3, < 2.0.0)
  rouge (>= 3.26.0, < 4.0.0)
  rspec (~> 3.0)
  rspec-mocks (~> 3.0)
  simplecov (~> 0.16.1)
  simplecov-lcov (~> 0.7.0)
  super_module (>= 1.4.1, < 2.0.0)
  text-table (>= 1.2.4, < 2.0.0)
  warbler (>= 2.0.5, < 3.0.0)

RUBY VERSION
   ruby 2.6.8p0 (jruby 9.3.1.0)

BUNDLED WITH
   2.3.5
```

--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/rubygems/rubygems/search?q=No+such+file+or+directory+-+%2FUsers%2Fandymaleh%2F.rvm%2Fgems%2Fjruby-9.3.3.0%40glimmer-dsl-swt%2Fgems%2Fpsych-4.0.3-java%2Fdeps.lst&type=Issues

If there aren't any reports for this error yet, please fill in the new issue form located at https://github.com/rubygems/rubygems/issues/new?labels=Bundler&template=bundler-related-issue.md, and copy and paste the report template above in there.
```

I know that this Pull Request fixed the issue. Will there be a new release of ruby-maven soon?

**Pull request merged**
