### PR TITLE
Make `rvmn` exit with a meaningful exit status

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
If the command it run under the hood failed, it should respect its status and fail too.

Helps with https://github.com/jruby/jruby-openssl/issues/199.

Also made an extra change so that the test suite at least starts.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
You might want to enable TravisCI in this repo, by the way :)

**Comment by kares** [comment]
Awesome David, thanks for looking into this.
@enebo any chance we could merge, [bump](https://github.com/jruby/ruby-maven/blob/master/lib/maven/ruby/version.rb#L3) and than push this to RGs?

**Comment by deivid-rodriguez** [comment]
No problem!

**Comment by headius** [comment]
Looks good, and +1 on getting testing enabled.

**Comment by headius** [comment]
We can release if we're ready for this, but there's at least one other open issue we should perhaps address.

**Pull request merged**
